version: '3'

services:
    db:
        image: postgres:12.3-alpine
        environment:
            POSTGRES_USER: roulette
            POSTGRES_PASSWORD: password
            POSTGRES_DB: roulette
        ports:
            - 5432:5432
        labels:
            com.symfony.server.service-prefix: 'DATABASE'

    test_db:
        image: postgres:12.3-alpine
        environment:
            POSTGRES_USER: roulette
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_roulette